apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cart-page-rs
  namespace: swasthik-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      web: cart
  template: # it defines which application that we had t deploy in the cluster (pod definition)
    metadata:
      labels:
        web: cart 
    spec: # it defines behavior of the pod
      containers:
      - name: cart-container
        image: muralisocial123/cart-page-test:1.0
        ports:
          - containerPort: 3000
