apiVersion: v1
kind: Service
metadata:
  name: cart-page-svc
spec:
  selector:
    web: cart # from deployment.yaml metadata web: cart
  ports:
  - port: 3002
    targetPort: 3000  # same as deployment.yaml port number
  type: LoadBalancer # this will create a load balancer in the cloud provider (AWS, GCP, Azure) and expose the service to the internet.
